## Understanding NumPy Array



In [1]:
import os
os.getcwd()
### Optional: os.chdir('C:\\Users\\didier.grimaldi\\Downloads\\output2\\')  # Provide the new path here

'C:\\Users\\didier.grimaldi\\OneDrive - La Salle\\Abril 2023 - BigData - Visualización para negocio\\Session 7 - 19.05 - Didier'

In [2]:
os.chdir('C:\\Users\\didier.grimaldi\\Downloads\\scripts')  # Provide the new path here

In [3]:
os.getcwd()

'C:\\Users\\didier.grimaldi\\Downloads\\scripts'

In [4]:
os.chdir('C:\\Users\\didier.grimaldi\\Downloads\\datos')  # Provide the new path here

In [5]:
os.getcwd()

'C:\\Users\\didier.grimaldi\\Downloads\\datos'

In [6]:
os.chdir('..\\scripts')

In [7]:
os.getcwd()

'C:\\Users\\didier.grimaldi\\Downloads\\scripts'

## Install libraries

In [ ]:
pip install numpy

## Create an array

In [2]:
import numpy as np
a = np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


In [3]:
a = np.arange(1,8)
print(a)

[1 2 3 4 5 6 7]


In [6]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


## create a matrix


In [4]:
a = np.array([[5,6],[7,8]])
print(a)

[[5 6]
 [7 8]]


In [5]:
# selecting array elements
print(a[0,1])

6


In [6]:
# Creating an array using arange()
a = np.arange(1,11,2) # start, stop, step
print(a)

[1 3 5 7 9]


In [8]:
t = np.random.random((5,5)) #create an array filled with random values
print(t)

[[0.62275817 0.77797638 0.18920183 0.13137872 0.64190057]
 [0.02281095 0.40319854 0.28288679 0.66360486 0.6827276 ]
 [0.45134745 0.03001429 0.20006264 0.60354908 0.92935222]
 [0.18164782 0.7962295  0.17641448 0.15991145 0.34389971]
 [0.62015624 0.97687329 0.46601296 0.75066562 0.31567635]]


## Manipulating array shapes

### using reshape() and flatten()

In [82]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
new_arr = arr.reshape(4,3)
print (new_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
new_arr = arr.reshape(-1,1)
print (new_arr)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [11]:
back_arr = new_arr.flatten()
print(back_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
vacio = []

### Creating a blank dataframe

In [40]:
import pandas as pd

In [41]:
df = pd.DataFrame()

In [42]:
# Create dictionary 
data = {'Name': ['Vijay', 'Sundar', 'Satyam', 'Indira'], 'Age': [23, 45, 46, 52 ]}   

# Create the pandas DataFrame 
df = pd.DataFrame(data)

# Header of dataframe. 
df.tail(1)

Name  Age
3  Indira   52

In [43]:
# Creating DataFrame using list of tuples/vectors.
data = [('Vijay', 23),( 'Sundar', 45), ('Satyam', 46), ('Indira',52)] 
# Create dataframe
df = pd.DataFrame(data, columns=['Name','Age'])
# Print dataframe header 
df.head()  

Name  Age
0   Vijay   23
1  Sundar   45
2  Satyam   46
3  Indira   52

# Exploratory Data Analysis

### Statistics 

In [48]:
# Import pandas library
import pandas as pd

# Create dataframe
sample_data = {'name': ['John', 'Alia', 'Ananya', 'Steve', 'Ben'], 
               'gender': ['M', 'F', 'F', 'M', 'M'], 
               'communication_skill_score': [40, 45, 23, 39, 39],
               'quantitative_skill_score': [38, 41, 42, 48, 32]}

data = pd.DataFrame(sample_data, columns = ['name', 'gender', 'communication_skill_score', 'quantitative_skill_score'])
data.head()

name gender  communication_skill_score  quantitative_skill_score
0    John      M                         40                        38
1    Alia      F                         45                        41
2  Ananya      F                         23                        42
3   Steve      M                         39                        48
4     Ben      M                         39                        32

In [18]:
# find mean of communication_skill_score column 
data['communication_skill_score'].mean(axis=0)

37.2

In [19]:
# find mode of communication_skill_score column
# the mode is the highest-occuring item in a group of observations
data['communication_skill_score'].mode()[0]

39

In [20]:
# find median of communication_skill_score column
# the median is the midpoint or middle value in a group of observations. It is the 50th percentile.
# the median is less affected by outliers and noise than the mean, and that is why it is considered a more
# statistic measure for reporting. 
data['communication_skill_score'].median()

39.0

In [62]:
column_range=data['communication_skill_score'].max()-data['communication_skill_score'].min()
print(column_range)

22


In [78]:
# Definición de la función para calcular el cuadrado de un número
def Super_Range(columna):
    """
    Es una función creada por el usuario del MBA Analytics de la UPC
    Calcula el cuadrado de x sin equivocarse.
    """
    output = columna.max()-columna.min()
    return output

In [80]:
Super_Range(data['quantitative_skill_score'])

16

In [22]:
# First Quartile
q1 = data['communication_skill_score'].quantile(.25)

# Third Quartile
q3 = data['communication_skill_score'].quantile(.75)

# Inter Quartile Ratio
iqr=q3-q1
print(iqr)

1.0


In [23]:
# Variance of communication_skill_score
data['communication_skill_score'].var()

69.2

In [24]:
# Standard deviation of communication_skill_score
data['communication_skill_score'].std()

8.318653737234168

In [25]:
# Describe dataframe
print(data.describe())

       communication_skill_score  quantitative_skill_score
count                   5.000000                  5.000000
mean                   37.200000                 40.200000
std                     8.318654                  5.848077
min                    23.000000                 32.000000
25%                    39.000000                 38.000000
50%                    39.000000                 41.000000
75%                    40.000000                 42.000000
max                    45.000000                 48.000000


In [ ]:
## Create the function Range

In [67]:
def Super_Mario_Range (column):
    """
    Es una función creada por el usuario del MBA Analytics de la UPC
    Calcula el range de una columna de un dataset.
    """
    column_range=column.max()-column.min()
    return (column_range)

In [83]:
Super_Mario_Range(arr)

11

In [69]:
help(Super_Mario_Range)

Help on function Super_Mario_Range in module __main__:

Super_Mario_Range(column)
    Es una función creada por el usuario del MBA Analytics de la UPC
    Calcula el range de una columna de un dataset.



### Now, let's learn how to implement the linear regression using the scikit-learn library

## Regression models

In [41]:
import os
os.getcwd()
### Optional: os.chdir('C:\\Users\\didier.grimaldi\\Downloads\\output2\\')  # Provide the new path here

'C:\\Users\\didier.grimaldi\\OneDrive - La Salle\\UPC\\Session 2 - 6 de mayo de 2023'

In [42]:
# Import pandas 
import pandas as pd
 
# Read the dataset using read_csv method
df = pd.read_csv("Advertising.csv")
 
# See the top-5 records in the data
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

## We split then the dataset into two groups

In [52]:
# Independent variables or Features
X = df[['TV', 'Radio', 'Newspaper']]
 
# Dependent or Target variable
y = df.Sales 

In [53]:
# Let's import the Linear Regression model
from sklearn.linear_model import LinearRegression

## Fitting a linear regression model

In [54]:
xradio = np.array(X.Radio)
print(xradio)

[37.8 39.3 45.9 41.3 10.8 48.9 32.8 19.6  2.1  2.6  5.8 24.  35.1  7.6
 32.9 47.7 36.6 39.6 20.5 23.9 27.7  5.1 15.9 16.9 12.6  3.5 29.3 16.7
 27.1 16.  28.3 17.4  1.5 20.   1.4  4.1 43.8 49.4 26.7 37.7 22.3 33.4
 27.7  8.4 25.7 22.5  9.9 41.5 15.8 11.7  3.1  9.6 41.7 46.2 28.8 49.4
 28.1 19.2 49.6 29.5  2.  42.7 15.5 29.6 42.8  9.3 24.6 14.5 27.5 43.9
 30.6 14.3 33.   5.7 24.6 43.7  1.6 28.5 29.9  7.7 26.7  4.1 20.3 44.5
 43.  18.4 27.5 40.6 25.5 47.8  4.9  1.5 33.5 36.5 14.  31.6  3.5 21.
 42.3 41.7  4.3 36.3 10.1 17.2 34.3 46.4 11.   0.3  0.4 26.9  8.2 38.
 15.4 20.6 46.8 35.  14.3  0.8 36.9 16.  26.8 21.7  2.4 34.6 32.3 11.8
 38.9  0.  49.  12.  39.6  2.9 27.2 33.5 38.6 47.  39.  28.9 25.9 43.9
 17.  35.4 33.2  5.7 14.8  1.9  7.3 49.  40.3 25.8 13.9  8.4 23.3 39.7
 21.1 11.6 43.5  1.3 36.9 18.4 18.1 35.8 18.1 36.8 14.7  3.4 37.6  5.2
 23.6 10.6 11.6 20.9 20.1  7.1  3.4 48.9 30.2  7.8  2.3 10.   2.6  5.4
  5.7 43.  21.3 45.1  2.1 28.7 13.9 12.1 41.1 10.8  4.1 42.  35.6  3.7
  4.9  9

In [56]:
xradio=xradio.reshape((-1, 1))
print(xradio)

[[37.8]
 [39.3]
 [45.9]
 [41.3]
 [10.8]
 [48.9]
 [32.8]
 [19.6]
 [ 2.1]
 [ 2.6]
 [ 5.8]
 [24. ]
 [35.1]
 [ 7.6]
 [32.9]
 [47.7]
 [36.6]
 [39.6]
 [20.5]
 [23.9]
 [27.7]
 [ 5.1]
 [15.9]
 [16.9]
 [12.6]
 [ 3.5]
 [29.3]
 [16.7]
 [27.1]
 [16. ]
 [28.3]
 [17.4]
 [ 1.5]
 [20. ]
 [ 1.4]
 [ 4.1]
 [43.8]
 [49.4]
 [26.7]
 [37.7]
 [22.3]
 [33.4]
 [27.7]
 [ 8.4]
 [25.7]
 [22.5]
 [ 9.9]
 [41.5]
 [15.8]
 [11.7]
 [ 3.1]
 [ 9.6]
 [41.7]
 [46.2]
 [28.8]
 [49.4]
 [28.1]
 [19.2]
 [49.6]
 [29.5]
 [ 2. ]
 [42.7]
 [15.5]
 [29.6]
 [42.8]
 [ 9.3]
 [24.6]
 [14.5]
 [27.5]
 [43.9]
 [30.6]
 [14.3]
 [33. ]
 [ 5.7]
 [24.6]
 [43.7]
 [ 1.6]
 [28.5]
 [29.9]
 [ 7.7]
 [26.7]
 [ 4.1]
 [20.3]
 [44.5]
 [43. ]
 [18.4]
 [27.5]
 [40.6]
 [25.5]
 [47.8]
 [ 4.9]
 [ 1.5]
 [33.5]
 [36.5]
 [14. ]
 [31.6]
 [ 3.5]
 [21. ]
 [42.3]
 [41.7]
 [ 4.3]
 [36.3]
 [10.1]
 [17.2]
 [34.3]
 [46.4]
 [11. ]
 [ 0.3]
 [ 0.4]
 [26.9]
 [ 8.2]
 [38. ]
 [15.4]
 [20.6]
 [46.8]
 [35. ]
 [14.3]
 [ 0.8]
 [36.9]
 [16. ]
 [26.8]
 [21.7]
 [ 2.4]
 [34.6]
 [32.3]


In [66]:
model_simple = LinearRegression().fit(xradio, y)

In [67]:
print('intercept:', model_simple.intercept_)
print('slope:', model_simple.coef_)

intercept: 9.311638095158283
slope: [0.20249578]


## Fitting a multi-linear regression model

In [68]:
# Fit the Linear Regression model
model_multiple=LinearRegression().fit(X, y)
print("Intercept:", model_multiple.intercept_)
print("Coefficients:", model_multiple.coef_)


Intercept: 2.9388893694594085
Coefficients: [ 0.04576465  0.18853002 -0.00103749]


# Evaluating regression model performance!

### with xradio

In [70]:
# Predict the values given test set
predictions_simple = model_simple.predict(xradio)

In [71]:
# Import the required libraries
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
 
# Evaluate mean squared error
print("Mean Squared Error(MSE):", mean_squared_error(y, predictions_simple))  
 
# Evaluate root mean squared error
print("Root Mean Squared Error(RMSE):", np.sqrt(mean_squared_error(y, predictions_simple)))
 
# Evaluate R2-square
print("R2-Square:",r2_score(y, predictions_simple))

Mean Squared Error(MSE): 18.09239774512544
Root Mean Squared Error(RMSE): 4.2535159274564185
R2-Square: 0.33203245544529525


### With X

In [73]:
# Predict the values given test set
predictions_multiple = model_multiple.predict(X)

In [74]:
# Import the required libraries
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
 
# Evaluate mean squared error
print("Mean Squared Error(MSE):", mean_squared_error(y, predictions_multiple))  
 
# Evaluate root mean squared error
print("Root Mean Squared Error(RMSE):", np.sqrt(mean_squared_error(y, predictions_multiple)))
 
# Evaluate R2-square
print("R2-Square:",r2_score(y, predictions_multiple))

Mean Squared Error(MSE): 2.784126314510936
Root Mean Squared Error(RMSE): 1.6685701407225697
R2-Square: 0.8972106381789522
